### ISSUE TITLE
initial configuration not working at all

### ISSUE THREAD

**Issue by whiggs** [mbegan/Box-PSModule#3]
When I run the boxcreateenv command, it provides me with the url that takes me to the page where it asks if the created app can have access to account, as seen below, but after I click grant access, it just returns me to the intial page I login to.  When I paste that into the console, I get:

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\box\box.psm1:289 char:9
+         throw($_.Exception.Message)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (You cannot call...ued expression.:String) [], RuntimeExcep 
   tion
    + FullyQualifiedErrorId : You cannot call a method on a null-valued expression.

If it is not altogether broken, it probably has to do with the "-name" parameter, which you were so kind as to provide no information as to what goes there whatsoever.  I wasted valuable time pasting any and every value in the app configuration into the window, all to the same result.  Why is this happening?
![2017-09-15 12_42_24-https___app box com_api_oauth2_authorize_response_type code client_id mzvved3y79](https://user-images.githubusercontent.com/11139575/30494258-6ade4740-9a15-11e7-9bfe-b5e15bd1aad5.png)

**Comment by mbegan** [comment]
Hi, as it relates to documentation of parameters see:

`powershell
Get-Help boxCreateEnv -full
`

Bottom line -name is an arbitrary value for you to be able to identify and distinguish between different environments that you might use. (e.g. _prod, dev, test_)

Sorry for the time "wasted" on this, i've never encountered the error you are experiencing and don't have access to a box env at the moment to test with.

The fact that you are getting returned to the initial login page makes me thing that perhaps you have configured appropriately configured your app in box [Register your application](https://box-content.readme.io/docs/oauth-20).  The page you see after clicking grant should be a page not found type page because you should have configured your Box application to redirect to localhost or 127.0.0.1 where there isn't a web server to process the request.  The entire goal here is to get the authorization code which will subsequently be exchanged for OAauth tokens.

again the details for that can be found [here](https://developer.box.com/docs/oauth-20#section-2-the-first-leg)

If you are still having problems after that i'll need a few additional errors to pinpoint the issue, the error at line 289 is an exception or two removed from what is likely the most meaningful error.

When you run it next and encounter an error can you please include the last 3 errors

`powershell
$Error[0..2]
`

-Matt

**Comment by gtatelive** [comment]
I feel the need to follow this post up with a thank you to both of you. I was having the same error but the explanation pointed to my box app not being setup correctly. I'm probably going to need to modify this code and would be happy to contribute back if desired.

**Comment by mbegan** [comment]
@gtatelive thanks for the follow up, i'm going to consider this issue closed.

I'll add a note to the top level docs to highlight the need to use localhost or 127.0.0.1 as the redirect_uri.

As far as contributions go, happy to accept pull requests.  I do NOT have access to a box org to test so I'll do a code review but cannot perform functional reviews.  If you can include details of test that will help me out.
